#!/usr/bin/env bash

#./manage.py dumpdata --exclude auth.permission --exclude contenttypes > user.json
rm -rf ./config/db.sqlite3 ./accounts/migrations/0001_initial.py ./assets
./manage.py makemigrations && \
./manage.py migrate && \
( ./manage.py loaddata user.json  && \
echo -e "\x1B[33m===>\x1B[0m Username: \x1B[1;32madmin\x1B[0m"  && \
echo -e "\x1B[33m===>\x1B[0m Password: \x1B[1;32madmin@123\x1B[0m" ) && \
./manage.py runserver
